# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160809_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_file',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
