# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20160812_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 8, 12, 7, 56, 9, 522128)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='/builder/'),
        ),
    ]
