# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20160812_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 8, 12, 8, 46, 58, 536472)),
        ),
    ]
