# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20160812_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='acad_details',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='resume',
            name='branch',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='cgpa',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='fname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='operating_systems',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='other_details',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='resume',
            name='packages',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='pos_of_resp',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='resume',
            name='programming_langauges',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='sports_details',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='resume',
            name='xiith_class_board',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='xiith_class_marks',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='xiith_class_school',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='xth_class_board',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='xth_class_marks',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='xth_class_school',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 10, 27, 34, 98748)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='nationality',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
