# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20160815_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='xth_class_year',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 10, 54, 58, 825356)),
        ),
    ]
