# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20160815_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 11, 14, 10, 100109)),
        ),
    ]
