# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20160815_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='xiith_class_year',
            field=models.CharField(default='', max_length=5),
        ),
    ]
