# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_resume_xiith_class_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='programming_langauges',
            new_name='programming_languages',
        ),
    ]
